### ISSUE TITLE
Cite MaCS in runMacs()

### ISSUE THREAD

**Issue by gregorgorjanc** [gaynorr/AlphaSimR#10]
Cite MaCS in runMacs()

Gary K Chen, Paul Marjoram, Jeffrey D Wall. Fast and flexible simulation of DNA sequence data. 2009, 19(1):136-42.  doi: 10.1101/gr.083634.108. Epub 2008 Nov 24
https://pubmed.ncbi.nlm.nih.gov/19029539/

**Comment by gaynorr** [comment]
Adding this citation to `runMacs` and `runMacs2`. The paper is already linked in the description, but it makes sense to mention it in the function documentation too.
