### ISSUE TITLE
randCross giving NA pheno

### ISSUE THREAD

**Issue by rthapa1** [gaynorr/AlphaSimR#11]
Hi, I am using randCross to make random crossing among the parents. The phenotype value is given to parents but after randCross, pheno is showing up as NA. What could be the issue? Thanks

**Comment by gregorgorjanc** [comment]
@rthapa1 Use `setPheno()` to phenotype individuals.

**Comment by gregorgorjanc** [comment]
@gaynorr This issue should be closed
