### ISSUE TITLE
estimation of allele frequency from genotype matrix derived from autotetraploid species

### ISSUE THREAD

**Issue by rthapa1** [gaynorr/AlphaSimR#12]
Hi, I have done simulation study to generate synthetic cultivar of autoteraploid species. At synthetic 2 (S2) generation, I want to estimate the allele frequency, I wonder if there is a way to estimate allele frequency from genotype data. There are 5 different types of genotypes observed.

**Comment by gregorgorjanc** [comment]
@rthapa1 AlphaSimR largely does not have functionality for these add-on analyses. However, since we simulate only biallelic sites allele frequency can be calculated simply by averaging allele dosages;)

**Comment by gregorgorjanc** [comment]
@gaynorr This issue should be closed
