### ISSUE TITLE
Changing dominance level for trait

### ISSUE THREAD

**Issue by rthapa1** [gaynorr/AlphaSimR#13]
Hi, Is there a way to set different level of dominance with alphaSimR? How could we set average degree of dominance independent of additive genetic variance for the trait?

**Comment by poca87** [comment]
You can control dominance when you set up your simulation parameters via two options; `meanDD` & `varDD`, for example inside `addTraitAD()` function. More details are available in AlphaSimR::traits vignette and AlphaSimR::SimParam help.

**Comment by rthapa1** [comment]
Is the additive effect fixed? What is the value of additive effect?

**Comment by poca87** [comment]
As I mentioned above, please have a look in AlphaSimR::traits vignette and AlphaSimR::SimParam help. For example, you could use aformentioned function to set both A & D, defaults are mean = 0 and var =1; 
```
SimParam$addTraitAD(
  nQtlPerChr,
  mean = 0,
  var = 1,
  meanDD = 0,
  varDD = 0,
  corA = NULL,
  corDD = NULL,
  useVarA = TRUE,
  gamma = FALSE,
  shape = 1,
  force = FALSE
)
```

**Comment by gregorgorjanc** [comment]
@gaynorr This issue should be closed
