### ISSUE TITLE
Using index of selection for selection in population

### ISSUE THREAD

**Issue by zjwinn** [gaynorr/AlphaSimR#197]
In the code I am writing, I am trying to preform stabilizing selection for plant height and heading date in wheat. I am able to successfully calculate a selection index which is returned as a matrix of [n, 1] where n is the number of individuals. I then attempt to use AlphaSimR::selectInd() to select using the index I have calculated. However, when I try to use the selection index as the input for "trait" as suggested in the example for AlphaSimR::selIndex(), I get the following error:

```{r}
Error in AlphaSimR::selectInd(pop = generation_0, nInd = 50, trait = index_of_selection,  : 
 ncol(response) == 1 is not TRUE
```

This appears to be an error message from the following sanity check in AlphaSimR::selectInd()

```{r}
response = getResponse(pop = pop, trait = trait, use = use, 
    simParam = simParam, ...)
if (is.matrix(response)) {
    stopifnot(ncol(response) == 1)
}
```

When I look at AlphaSimR:::getResponse, it appears that it is trying to pull a column from the population phenotypes. However, you cannot add the selection index as a phenotype to the target population. I am confused how to proceed.  I have ran the example in AlphaSimR::selIndex() and it works. It calls on something that does not exist, I will paste here for reference.

```{r}
#Create founder haplotypes
founderPop = quickHaplo(nInd=10, nChr=1, segSites=10)

#Set simulation parameters
SP = SimParam$new(founderPop)

#Model two genetically correlated traits
G = 1.5*diag(2)-0.5 #Genetic correlation matrix
SP$addTraitA(10, mean=c(0,0), var=c(1,1), corA=G)
SP$setVarE(h2=c(0.5,0.5))

#Create population
pop = newPop(founderPop, simParam=SP)

#Calculate Smith-Hazel weights
econWt = c(1, 1)
b = smithHazel(econWt, varG(pop), varP(pop))

#Selection 2 best individuals using Smith-Hazel index
#selIndex is used as a trait
pop2 = selectInd(pop, nInd=2, trait=selIndex, 
                 simParam=SP, b=b)
```

**Comment by gregorgorjanc** [comment]
@zjwinn you can pass a function to the `trait` argument (this is what the example above that you have pasted does) - the function must return a vector `n*1` by working on variables in `use` argument. From a quick reading of your post above I think you are passing an `n*1`, but the function expects a single value (trait number or name) or a function.

**Comment by zjwinn** [comment]
@gregorgorjanc I have passed the selectInd function the selIndex function in the trait argument. Now I am reciving this error message:

```{r}
Error in Y %*% b : non-conformable arguments
```

I belive this is because I am trying to do two rounds of selection. One with a index of selection made for stabalizing traits (plant height, and heading date) and then a following index made on agronomically important traits (grain yield, stripe rust resistance, etc.). This means the vector b is not the same length as the dim of Y, and thus they cannot be multiplied. Is there any way to specify only a subset of the traits to be used in the selection index? I tried defining "Y" in the selectInd function, and it threw an error as well.

```{r}
Error in if (scale) { : the condition has length > 1
```

I am assuming this has something to do with the "scale" argument of the selIndex function. I have tried adding that option and then I get this error:

```{r}
Error in trait(pop@pheno, ...) : unused argument (pop@pheno)
```

This is the state of the current code:

```{r}
# Set phenotype for example population using average number of reps in current data
generation_0 <- AlphaSimR::setPheno(generation_0, 
                                    h2 = trait_h2,
                                    reps = round(trait_reps), 
                                    varE = trait_Verror)

# Perform stabilizing selection index
economic_weights <- c(-1, # Plant Height
                      -1) # Heading Date
names(economic_weights) <- c("plant_height",
                             "heading_date")

# Get varG and varP for index
varG <- AlphaSimR::varG(generation_0)
varG <- varG[rownames(varG) %in% names(economic_weights),
             colnames(varG) %in% names(economic_weights)]
varP <- AlphaSimR::varP(generation_0)
varP <- varP[rownames(varP) %in% names(economic_weights),
             colnames(varP) %in% names(economic_weights)]

# Calculate squared deviation
Y <- data.frame(plant_height = (generation_0@pheno[,"plant_height"]-35)^2,
                heading_date = (generation_0@pheno[,"heading_date"]-105)^2)
Y <- as.matrix(Y)

# Create index of selection
index_of_selection <- AlphaSimR::smithHazel(econWt = economic_weights,
                                            varG = varG,
                                            varP = varP)
# index_of_selection <- AlphaSimR::selIndex(Y, index_of_selection)

# Select top 50 optimal heading and height data
breeding_population <- AlphaSimR::selectInd(pop = generation_0, 
                                            nInd = 50,
                                            trait = AlphaSimR::selIndex,
                                            selectTop = TRUE,
                                            returnPop = TRUE,
                                            Y = Y,
                                            b = index_of_selection,
                                            scale = FALSE)
```

Thank you for your help

- Zach

**Comment by gregorgorjanc** [comment]
@zjwinn can you share a reproducible example I can run on my end?

**Comment by gregorgorjanc** [comment]
@zjwinn this looks like an involved example! Cool! Looking into it.

**Comment by gregorgorjanc** [comment]
@zjwinn I think the issue is that you are trying to do selection on 2 traits, but you have more traits in the population. Running this works:

```
> AlphaSimR::selIndex(Y = Y, b = index_of_selection)
               [,1]
  [1,]   -9.8891145
  [2,]  -66.3330382
```

as does

```
> AlphaSimR::selectInd(pop = generation_0, 
+                                             nInd = 50,
+                                             use = "pheno")
An object of class "Pop" 
Ploidy: 2 
Individuals: 50 
Chromosomes: 21 
Loci: 21000 
Traits: 8 
```

but

```
> breeding_population <- AlphaSimR::selectInd(pop = generation_0, 
+                                             nInd = 50,
+                                             use = "pheno",
+                                             trait = AlphaSimR::selIndex,
+                                             Y = Y,
+                                             b = index_of_selection,
+                                             scale = TRUE)
Error in trait(pop@pheno, ...) : unused argument (pop@pheno)
```

and when I omit `Y`

```
> breeding_population <- AlphaSimR::selectInd(pop = generation_0, 
+                                             nInd = 50,
+                                             use = "pheno",
+                                             trait = AlphaSimR::selIndex,
+                                             b = index_of_selection,
+                                             scale = TRUE)
Error in scale(Y) %*% b : non-conformable arguments
```

because we are taking all phenotype traits (8) while index has 2 weights.

if I instead do 

```
> economic_weights <- rep(0, times = length(traits))
> names(economic_weights) <- traits
> economic_weights[c("plant_height", "heading_date")] <- c(-1, -1)
> index_of_selection <- AlphaSimR::smithHazel(econWt = economic_weights,
+                                             varG = AlphaSimR::varG(generation_0),
+                                             varP = AlphaSimR::varP(generation_0))
> breeding_population <- AlphaSimR::selectInd(pop = generation_0, 
+                                             nInd = 50,
+                                             use = "pheno",
+                                             trait = AlphaSimR::selIndex,
+                                             b = index_of_selection,
+                                             scale = TRUE)
> breeding_population
An object of class "Pop" 
Ploidy: 2 
Individuals: 50 
Chromosomes: 21 
Loci: 21000 
Traits: 8 
```

WARNING: This might not be selection index calculation you want - I am only showing how code works.

You can also always do stuff like

```
selIndex = generation_0@pheno %*% index_of_selection
ord = order(selIndex, decreasing = TRUE)[1:50]
breeding_population = generation_0[ord]
```

I wrote above on the fly, so you should check if this is what you want - I am focusing on how you can use AlphaSimR code for what you want to do.

@gaynorr might have further thoughts om the above.

**Comment by zjwinn** [comment]
@gregorgorjanc I will go ahead with the indexing method you proposed in the latter half of your explanation for now. As I understand the other method, you propose making an index with weights equal to 0 for all traits not involved in selection. This might work; however, I need to select lines which are converging on an optimum heading date and plant height, which requires calculating the deviation from the optimum featured in my code as me calculating Y:

```{r}
Y <- data.frame(plant_height_sd = (generation_0@pheno[,"plant_height"]-35)^2,
                heading_date_sd = (generation_0@pheno[,"heading_date"]-105)^2)
Y <- as.matrix(Y)
```

So, I think just going to use the indexing and sub-setting workaround proposed in the second half for now. Thanks for working on this.

**Comment by gaynorr** [comment]
@zjwinn, I think Gregor's suggestion works well. You can also replace `selIndex` with your own custom function. This can be useful if it is something you're using a lot, because you won't have to copy code as much. Here is an example based on your example above: 

```
# Custom function
# Y is the matrix of phenotypes coming from a population
# b is a vector of weights coming from the user
foo = function(Y, b){
  Y = data.frame(plant_height_sd = (Y[,"plant_height"]-35)^2,
                 heading_date_sd = (Y[,"heading_date"]-105)^2)
  Y = as.matrix(Y)
  return(Y %*% b)
}


# Select top 50 optimal heading and height data
breeding_population <- AlphaSimR::selectInd(pop = generation_0, 
                                            nInd = 50,
                                            trait = foo,
                                            use = "pheno",
                                            selectTop = TRUE,
                                            returnPop = TRUE,
                                            b = index_of_selection)
```

My above example only shows how to implement your code. I'm not sure if it is the best way to do stabilizing selection. I'm a little confused as to why you are using the Smith-Hazel function, because I've never seen this method used with an index like yours. Without using this function, what you're doing is makes sense to me. Thus, I'm not sure if the use of the Smith-Hazel function is just a copy from a previous example or a methodology I'm not aware of. 

If it's of any interested, I have some examples for doing stabilizing selection using absolute values and genomic predictions. I also have code for using a restricted index for phenotypic selection.

**Comment by zjwinn** [comment]
@gaynorr, I was emulating some code I saw on the internet. If you have copies of your code that you're willing to share, please send them my way. Also, if you have any recommendations for literature, I would be highly appreciative. I am not new to plant breeding, but I am relatively new to using formal  index of selection methods.

**Comment by gaynorr** [comment]
@zjwinn, the approach of using squared deviations that you showed should work. I just don't know how well it works relative to any other approach. I'm just not sure that there is any reason to use the Smith-Hazel function. It's intended for linear indices using economic weights.

The approach that I common see used in both plant and animal breeding to this type of problem is the desired gains index. There are a few papers on it that might be useful.

Here is one from some of my former colleges that shows an AlphaSimR simulation and written for a broader audience: 
https://www.biorxiv.org/content/10.1101/2024.07.21.603926v1

There's a more technical one here that discusses optimization of the index:
https://www.frontiersin.org/journals/plant-science/articles/10.3389/fpls.2024.1337388/full

There's also a very math heavy paper here that connects the desired gains index to the restricted index:
https://onlinelibrary.wiley.com/doi/10.1111/jbg.12845#jbg12845-bib-0046

**Comment by gaynorr** [comment]
I have previously used the function before in a simulation. It's based off the restricted index described in the last paper. I used the true genetic and phenotypic variance in this function. It was only used in a burn-in to roughly approximate what a breeder would do to hold a number of traits constant (4 in this case). The idea here was to then switch to an approach using estimated data after the burn-in to test different methods.

```

#Function for restricted index
#Attempts to keep the mean of the first n traits from changing
restrIndex = function(pop, #Population to apply index to
                      n=4, #Number of traits to keep at zero
                      w=c(rep(0,4),1)){ #Economic weights of index
  P = varP(pop) #Phenotypic variance
  G = varG(pop) #Genetic variance
  I = diag(length(w))
  C = cbind(diag(n),matrix(0,nrow=n,ncol=(length(w)-n)))
  Gr = C%*%G
  Pinv = solve(P)
  b = (I-Pinv%*%t(Gr)%*%solve(Gr%*%Pinv%*%t(Gr))%*%Gr)%*%Pinv%*%G%*%w
  return(b/sqrt(sum(b^2))) #Scale index to unit vector
}
```

I would use this function like similarly to the code below. Note that I had to order the traits in a very particularly way to match the way I coded the above function.

```
b = restrIndex(PYT)
AYT = selectInd(PYT, nAYT, trait=selIndex, b=b)
```
