### ISSUE TITLE
Cite the AlphaSimR paper and provide citation

### ISSUE THREAD

**Issue by gregorgorjanc** [gaynorr/AlphaSimR#2]
We should cite the AlphaSimR paper and provide citation

https://doi.org/10.1093/g3journal/jkaa017

**Comment by gaynorr** [comment]
I updated the link to the advanced copy and I will change it to the final copy when it becomes available.

**Comment by gregorgorjanc** [comment]
This is now the finalised version
https://academic.oup.com/g3journal/article/11/2/jkaa017/6025179
