### ISSUE TITLE
Add trait names to ease downstream scripting

### ISSUE THREAD

**Issue by gregorgorjanc** [gaynorr/AlphaSimR#24]
The idea is that we would be able to do something like this

```
pop@gv[, "traitX"]
gv(pop, trait = "traitX"
...


pop@pheno[, "traitX"]
pheno(pop, trait = "traitX"
...
```

**Comment by gaynorr** [comment]
Noted. I've added specific names for loci and chromosomes as part of ongoing development to better facility reading in real data. I can continue down this route by adding names to SNP chips and traits.
