### ISSUE TITLE
addTraitAG (error with only 1 QTL)

### ISSUE THREAD

**Issue by haono** [gaynorr/AlphaSimR#29]
Hi
I'm having an error when simulating a wheat breeding program (R version 3.6.3 and AlphaSimR_1.0.4 R6_2.4.1). The error was found using the code below:

```
founderGenomes <- runMacs(
  nInd = 70,
  nChr = 21,
  segSites = 1000 + 1,
  inbred = TRUE,
  species = "WHEAT"
)

SP <<- SimParam$new(founderGenomes)
SP$restrSegSites(1,1000)
SP$addSnpChip(nSnpPerChr = 1000)
SP$addTraitAG(
  nQtlPerChr = 1,
  mean = 4,
  var = 0.1,
  varGxE = 0.2
)
```

The error was arised by pickLoci called in addTraitAG. However, I've noticed that running the command without addSnpChip works. Apparently by using SP$addSnpChip(nSnpPerChr = 1000), it is inserted into invalidQtl the entire set of positions, including the QTL (line 1691 of Class-SimParam.R, `self$invalidQtl[[x]] = sort(union(tmp, self$invalidQtl[[x]]))`.

**Comment by gaynorr** [comment]
Thanks for reporting the error. I'll look into it more and plan to have a fix for the next version of the package. It appears I've made a mistake in my coding and the restriction of sites doesn't work correctly when the number of QTL and/or SNP is 1.

For now, you can run your code without `SP$restrSegSites(1,1000)` and get the desired behavior of having a QTL position that doesn't coincide with a SNP position.

**Comment by gaynorr** [comment]
Issue has been resolved in the devel branch and will be fixed in the next AlphaSimR release.
