### ISSUE TITLE
Document species and demography models in runMacs

### ISSUE THREAD

**Issue by gregorgorjanc** [gaynorr/AlphaSimR#3]
We have to document species and demography models in runMacs 

For CATTLE we have
https://academic.oup.com/mbe/article/30/9/2209/1002512

For MAIZE we follow 
https://www.research.ed.ac.uk/en/publications/evaluation-of-genomic-selection-training-population-designs-and-g

For WHEAT we follow
https://acsess.onlinelibrary.wiley.com/doi/pdf/10.2135/cropsci2016.09.0742

For EUROPEAN we follow
???

**Comment by gaynorr** [comment]
I'm adding these citation in and I'm dropping EUROPEAN, because it just takes too long to run (days) to make sense to support. I

**Comment by gregorgorjanc** [comment]
Cool call re EUROPEAN. Eventually we should provide support to leverage stdpopsim, but the underlying msprime (backward in time) is to slow for now - maybe SLiM could help (forward in time). There is time for that in the future.
