### ISSUE TITLE
Selection of id in pop object is having issues since update 1.1.2

### ISSUE THREAD

**Issue by LucianoRogerio** [gaynorr/AlphaSimR#42]
Hi

I got the following issues since the new update 1.1.2:
`"assignment of an object of class “matrix” is not valid for @‘geno’ in an object of class “Pop”`

I was selecting individuals from a population using a vector of a character class or numeric like the following example
```
id <- c("11", "15", ..., "150")
pop[id]
```
and that returned a new pop object, but only with the individuals I asked.
Could you see or recommend how should I procceed to fix this?
Thanks for your work

**Comment by gregorgorjanc** [comment]
Hi @LucianoRogerio it would be very useful if you can provide a reproducible example - a complete set of the code we can run on our end - like you see in the help pages.

Thanks!

**Comment by LucianoRogerio** [comment]
Hi @gregorgorjanc 
I tried my test script again running the burn-in phase, and the issue vanished, it seems to be related to my Burn-in test results RDS file that I was previously using.
So this is not an issue from AlphaSimR.
Sorry for taking your time
Have a great week
