### ISSUE TITLE
Bug when running a multi-trait breeding programme: example using correlation matrix for additive genetic values

### ISSUE THREAD

**Issue by Prof-ThiagoOliveira** [gaynorr/AlphaSimR#43]
I found an issue when simulating multi-trait breeding programmes.   AlphaSimR uses SDV decomposition to simulate additive, dominance, and other effects. Thus, SVD is identical to` QDQ^T` for positive definite matrices. However, any negative eigenvalues in `D` for indefinite matrices become positive in `Σ`. I am saying that because AlphaSimR does not check if the correlation matrix for Additive and Dominance are positive semi-definite, which can lead to a big problem when simulating the breeding programme. Let me show you an example with Cattle.

- Defining global parameters:

```
########################################################################
## Script purpose: AlphaSimR issue
## Date: 2022-02-21
## Author: Thiago de Paula Oliveira
########################################################################
library(gdata)
library(corrplot)
library(AlphaSimR)

nburnin <- 20
nfuture <- 20
#-----------------------------------------------------------------------
# Definitions
#-----------------------------------------------------------------------
nInd = 2000 # number of individuals
nQtl = 200 # number of QTL's / Chromosome
nSnp = 266 # number of SNPs / Chromosome
nChr = 4 # number of Chromosomes


# Founders parameters
meanG <- 0
sigma2g <- 0.3 

# Herdability
h2 <- 0.3

# Error
(sigma2 <- sigma2g*(1/h2 - 1))

# Number of animals to be selected
nDams <- nInd/2 # no selection
nSires <- 5  

nTraits <- 20
``` 

- Defining the additive correlation matrix between traits (`corA` in `SP$addTraitA`).
- I am simulating in a way that there are some negative eigenvalues. 

```
AmatrixP1 <- diag(1, nTraits)
offDiagP1 <- runif(length(AmatrixP1[upper.tri(AmatrixP1)]),
                   min=0.85, max=1)
AmatrixP1[upper.tri(AmatrixP1)] <- offDiagP1
lowerTriangle(AmatrixP1) <- upperTriangle(AmatrixP1, byrow=TRUE)

#-----------------------------------------------------------------------
# Correlation between location for Programme B
#-----------------------------------------------------------------------  
AmatrixP2 <- diag(1, nTraits)
offDiagP2 <- runif(length(AmatrixP2[upper.tri(AmatrixP2)]),
                   min=0.85, max=1)
AmatrixP2[upper.tri(AmatrixP2)] <- offDiagP2
lowerTriangle(AmatrixP2) <- upperTriangle(AmatrixP2, byrow=TRUE)
#-----------------------------------------------------------------------
# Correlation between location across Programmes
#-----------------------------------------------------------------------
AmatrixP1P2 <- diag(runif(nTraits, min= 0.2, max=1))
for (i in 1:nrow(AmatrixP1P2)) {
  AmatrixP1P2[i,] <- AmatrixP1P2[i,i]
}

AmatrixP1P2[upper.tri(AmatrixP1P2)] <- AmatrixP1P2[upper.tri(AmatrixP1P2)]*
  1/2*(offDiagP1+offDiagP2)

lowerTriangle(AmatrixP1P2) <- upperTriangle(AmatrixP1P2, byrow=TRUE)

#-----------------------------------------------------------------------
# Correlation Matrix
#-----------------------------------------------------------------------
mCor <- rbind(cbind(AmatrixP1, AmatrixP1P2),
              cbind(AmatrixP1P2, AmatrixP1))

#=======================================================================
# Eigen Values
#=======================================================================
plot(eigen(mCor)$values, ylab = "Eigen values")
abline(h=0)
```

[eigenvalues.pdf](https://github.com/gaynorr/AlphaSimR/files/8111249/eigenvalues.pdf)

```
#=======================================================================
# Correlation plot
#=======================================================================
corrplot(mCor)
```
[Assumed correlation.pdf](https://github.com/gaynorr/AlphaSimR/files/8111246/Assumed.correlation.pdf)

- Creating Founders

```
# Generate initial haplotypes
founderPop <- runMacs(nInd = nInd,  nChr = nChr, segSites = nQtl + nSnp,
                      species = "CATTLE", ploidy = 2L)
```

- Generating SP parameters

```
SP = SimParam$new(founderPop)
SP$restrSegSites(nQtl,nSnp)
if (nSnp > 0) {
  SP$addSnpChip(nSnp)
}
#-----------------------------------------------------------------------
# Adding Traits
#-----------------------------------------------------------------------
#debugonce(SP$addTraitAD)
SP$addTraitA(nQtl,
            mean = rep(meanG, 2*nTraits),
            var = rep(sigma2g, 2*nTraits),
            corA   = mCor)
#-----------------------------------------------------------------------
# Adding error structure
#-----------------------------------------------------------------------
SP$setVarE(varE = rep(sigma2, 2*nTraits)) #
```
- New population

```
Parents = newPop(founderPop)
```

- Correlation between genetic values

```
corrplot(cor(Parents@gv))
```

[corAlphaSimR.pdf](https://github.com/gaynorr/AlphaSimR/files/8111255/corAlphaSimR.pdf)

Running this example, you will see that the observed correlation calculated from `Parents@gv` is entirely different from the assumed one. Therefore, I suggest you add a warning message when this situation happens. Otherwise, the simulated breeding programme won't be the assumed one.

**Comment by gaynorr** [comment]
Thanks for the detailed example. I originally let these types of matrices pass through, because I was allowing for cases where you either want to force a correlation of 1 between some effects and/or you are using estimated correlation matrices that are not positive semi-definite. A warning message does make sense to provide a little more transparency to the user and to flag potential problems.

I'll note that setting the correlation between additive effects nicely translates approximately the same gv correlations when only additive effects. However, dominance correlations don't have such a nice property. This is particularly the case when using directional dominance. It would be desirable for the user to be able to assign a correlation between breeding values directly when dominance is present, but I currently don't have a solution for this.
