### ISSUE TITLE
Allow for the user to pick haplotype-pairs when creating a new Pop-class from Map-Pop

### ISSUE THREAD

**Issue by janaobsteter** [gaynorr/AlphaSimR#57]
This would be useful for example in honeybees, since we don't want individuals that are homozygous at the _csd_ to be created from the founders

**Comment by gaynorr** [comment]
@janaobsteter are you thinking about doing this after calling runMacs or at some other time?

**Comment by gregorgorjanc** [comment]
@gaynorr yes after runMacs - this would essentially (conceptually) enable imposing a pedigree when creating a newPop from MapPop.
