### ISSUE TITLE
AlphaSimR

### ISSUE THREAD

**Issue by rthapa1** [gaynorr/AlphaSimR#8]
Hi,

I want to simulate the breeding pipeline for developing synthetic cultivars. I wonder if AlphaSimR could be used.

Thanks

**Comment by gregorgorjanc** [comment]
Dear @rthapa1 yes AlphaSimR can be used for this! You will have to develop an R script using AlphaSimR functions to model your breeding pipeline. We are developing a set of tutorials, an on-line course and a compendium of breeding programme simulations that could help you in your work. Stay tunned.

**Comment by rthapa1** [comment]
Thank you for your response. I wonder if there is a way to set different deviations from Hardy equilibrium. 
The following script assumes HW equilibrium. I want to test at different levels of deviations of HWE.
Founder = runMacs(nInd=200, nChr=10, 
                       segSites=1000, ploidy=2)

**Comment by gregorgorjanc** [comment]
@rthapa1 this coalescent simulation via MaCS is just a starting point. You can now impose population structure, mating, and/or selection via R scripting that will impose deviations from HWE.

**Comment by rthapa1** [comment]
When I do selection of certain individuals from the founder population and do random crossing among themselves, I know there would be deviation from HWE but I wonder if there is a way to set particular value of deviation.

**Comment by gregorgorjanc** [comment]
Well, in reality, we get deviation from HWE due to a particular process, and this is what AlphaSimR enables you to do so. This is the cleanest way of doing this. Fudging the genomes is tricky. You can do it, by importing your own haplotypes if this is what you want to achieve.

**Comment by gregorgorjanc** [comment]
@rthapa1 You will need to provide more information than just this error message. It seems you are going beyond the allocated array/vector dimensions somewhere or there is a bug.

**Comment by rthapa1** [comment]
I found that it was due to segSites = 10000 setting. If I set segSites higher than SP$addSnpChip(1000), the issue was resolved.
