### ISSUE TITLE
Get AlphaSimR internet domain

### ISSUE THREAD

**Issue by gregorgorjanc** [gaynorr/AlphaSimR#96]
We could get an internet domain for AlphaSimR, say AlphaSimR.info.

@gaynorr I can purchase this against a grant and then we point the domain to a PKgDown folder of documentation and vignettes.

Shall I proceed?

**Comment by gaynorr** [comment]
We do get an address for GitHub pages without having to register a domain: https://gaynorr.github.io/AlphaSimR/. I really just need to get some work done on the webpage.
